[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200